### ISSUE TITLE
Attribute values begin with lower case

### ISSUE THREAD

**Issue by yisibl** [yuezk/postcss-filter-gradient#2]
MSDN of the sample are lower case, the mainstream CSS framework is also the beginning of the lower case, please keep the same. And move the `GradientType` to the end.

**If there is an option to control the size of the color to write it would be better.**

> ``` html
> <DIV ID="oDiv" STYLE="height:120px; color:green; filter: 
>             progid:DXImageTransform.Microsoft.gradient(enabled='false',
>                 startColorstr=#550000FF, endColorstr=#55FFFF00)" >
>         A simple gradient   
>     </DIV>
> ```
> 
> https://msdn.microsoft.com/zh-cn/library/ms532997(v=vs.85).aspx
## Output:

``` css
button {
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#f2f2f2', endColorstr='#e6e6e6', GradientType=0);
}
```
## See also:
- https://github.com/twbs/bootstrap/blob/v2.3.2/less/mixins.less#L426
  *https://github.com/ecomfe/est/blob/9d2d29915d62744db18208c2865e771e058c303b/src/compatibility.less#L716
